# Generated by Django 5.2.7 on 2025-10-26 10:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ATHLETE', 'Athlete'), ('COACH', 'Coach')], default='ATHLETE', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='ReadinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('sleep_quality', models.PositiveIntegerField(help_text='Rate your sleep quality from 1 (Very poor/restless/<5hrs) to 10 (Excellent/deep/uninterrupted)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_fatigue', models.PositiveIntegerField(help_text='Rate your energy from 1 (Exhausted/heavy) to 10 (Fully energised/alert)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('muscle_soreness', models.PositiveIntegerField(help_text='Rate your muscle soreness from 1 (Extremely sore/tight) to 10 (No soreness/loose/ready)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_stress', models.PositiveIntegerField(help_text='Rate your mood from 1 (Very stressed/low mood) to 10 (Calm/positive/clear-headed)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('motivation', models.PositiveIntegerField(help_text='Rate your motivation from 1 (Not motivated) to 10 (Extremely motivated/excited)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('nutrition_quality', models.PositiveIntegerField(help_text='Rate your nutrition from 1 (Poor/skipped meals) to 10 (Excellent/balanced meals)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('hydration', models.PositiveIntegerField(help_text='Rate your hydration from 1 (Dehydrated/dry mouth) to 10 (Well-hydrated/clear urine/alert)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('readiness_score', models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'unique_together': {('athlete', 'date_created')},
            },
        ),
    ]
