# Generated by Django 5.2.7 on 2025-10-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('TRAINING', 'Training Day'), ('MATCH', 'Match Day'), ('RECOVERY', 'Recovery Day'), ('REST', 'Rest Day'), ('PREP_TRAVEL', 'Prep/Travel Day')], max_length=20, unique=True)),
                ('min_expected', models.PositiveIntegerField(help_text='Minimum expected readiness percentage')),
                ('max_expected', models.PositiveIntegerField(help_text='Maximum expected readiness percentage')),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='TeamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_schedule', models.JSONField(default=dict, help_text='Weekly schedule mapping weekdays to day tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.team')),
            ],
        ),
    ]
