# Generated by Django 5.2.7 on 2025-10-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_daytag_teamschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamschedule',
            name='date_overrides',
            field=models.JSONField(default=dict, help_text='Specific date overrides for the weekly schedule'),
        ),
    ]
