# Generated by Django 5.2.7 on 2025-10-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teamschedule_date_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='target_readiness',
            field=models.PositiveIntegerField(default=100, help_text='Target team readiness percentage (0-100)'),
        ),
    ]
