# Generated by Django 5.2.7 on 2025-10-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_target_readiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytag',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
