# Generated by Django 5.2.7 on 2025-10-29 23:07

from django.db import migrations


def migrate_team_schedule_data(apps, schema_editor):
    """
    Convert old string-based tags to new TeamTag ID system.
    Creates default TeamTags for each team and updates their schedules.
    """
    Team = apps.get_model('core', 'Team')
    TeamTag = apps.get_model('core', 'TeamTag')
    TeamSchedule = apps.get_model('core', 'TeamSchedule')
    
    # Default tags to create for each team
    default_tags = [
        {'name': 'Training', 'target': 70, 'color': '#0d6efd'},
        {'name': 'Match', 'target': 85, 'color': '#198754'},
        {'name': 'Recovery', 'target': 55, 'color': '#ffc107'},
        {'name': 'Rest', 'target': 75, 'color': '#17a2b8'},
        {'name': 'Prep/Travel', 'target': 65, 'color': '#6c757d'},
    ]
    
    # Old string to new tag name mapping
    old_to_new = {
        'TRAINING': 'Training',
        'MATCH': 'Match', 
        'RECOVERY': 'Recovery',
        'REST': 'Rest',
        'PREP_TRAVEL': 'Prep/Travel',
    }
    
    for team in Team.objects.all():
        # Create default tags for this team
        tag_mapping = {}  # old_name -> new_tag_id
        for tag_data in default_tags:
            tag, created = TeamTag.objects.get_or_create(
                team=team,
                name=tag_data['name'],
                defaults={
                    'target': tag_data['target'],
                    'color': tag_data['color']
                }
            )
            tag_mapping[tag_data['name']] = tag.id
        
        # Update team schedule
        try:
            schedule = TeamSchedule.objects.get(team=team)
            
            # Convert weekly schedule
            new_weekly = {}
            for weekday, old_tag in schedule.weekly_schedule.items():
                if old_tag in old_to_new:
                    new_tag_name = old_to_new[old_tag]
                    if new_tag_name in tag_mapping:
                        new_weekly[weekday] = tag_mapping[new_tag_name]
                else:
                    # Default to Training if unknown
                    new_weekly[weekday] = tag_mapping['Training']
            
            # Convert date overrides
            new_overrides = {}
            for date_str, old_tag in schedule.date_overrides.items():
                if old_tag in old_to_new:
                    new_tag_name = old_to_new[old_tag]
                    if new_tag_name in tag_mapping:
                        new_overrides[date_str] = tag_mapping[new_tag_name]
                else:
                    # Default to Training if unknown
                    new_overrides[date_str] = tag_mapping['Training']
            
            # Update the schedule
            schedule.weekly_schedule = new_weekly
            schedule.date_overrides = new_overrides
            schedule.save()
            
        except TeamSchedule.DoesNotExist:
            # Create new schedule with default Training tag
            TeamSchedule.objects.create(
                team=team,
                weekly_schedule={weekday: tag_mapping['Training'] for weekday in ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']},
                date_overrides={}
            )


def reverse_migrate_team_schedule_data(apps, schema_editor):
    """
    Reverse migration - convert back to string tags (for rollback if needed).
    """
    TeamTag = apps.get_model('core', 'TeamTag')
    TeamSchedule = apps.get_model('core', 'TeamSchedule')
    
    # Delete all TeamTags
    TeamTag.objects.all().delete()
    
    # Reset schedules to empty (they'll get defaults on next access)
    for schedule in TeamSchedule.objects.all():
        schedule.weekly_schedule = {}
        schedule.date_overrides = {}
        schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teamtag_delete_daytag'),
    ]

    operations = [
        migrations.RunPython(migrate_team_schedule_data, reverse_migrate_team_schedule_data),
    ]