# Generated by Django 5.2.7 on 2025-10-30 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_migrate_team_schedule_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtag',
            name='target',
        ),
        migrations.AddField(
            model_name='teamtag',
            name='target_max',
            field=models.PositiveIntegerField(default=80, help_text='Maximum acceptable readiness percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='teamtag',
            name='target_min',
            field=models.PositiveIntegerField(default=60, help_text='Minimum acceptable readiness percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
