# Generated by Django 5.2.7 on 2025-10-30 00:45

from django.db import migrations


def migrate_target_to_range(apps, schema_editor):
    """
    Convert single target values to ranges based on tag type.
    """
    TeamTag = apps.get_model('core', 'TeamTag')
    
    # Define range mappings based on tag names
    range_mappings = {
        'Training': (60, 80),      # Moderate intensity
        'Match': (80, 95),         # High intensity
        'Recovery': (40, 60),      # Low intensity
        'Rest': (70, 90),          # Good rest
        'Prep/Travel': (50, 70),   # Moderate with travel
        'Gym Work': (55, 75),      # Gym training
        'Heavy Training': (45, 65), # High intensity training
    }
    
    for tag in TeamTag.objects.all():
        # Get range based on tag name, default to ±10 around current target
        if tag.name in range_mappings:
            target_min, target_max = range_mappings[tag.name]
        else:
            # For unknown tags, create a ±10 range around the current target
            current_target = getattr(tag, 'target', 70)  # Fallback to 70 if target doesn't exist
            target_min = max(0, current_target - 10)
            target_max = min(100, current_target + 10)
        
        # Set the new range fields
        tag.target_min = target_min
        tag.target_max = target_max
        tag.save()


def reverse_migrate_target_to_range(apps, schema_editor):
    """
    Reverse migration - convert ranges back to single targets (midpoint).
    """
    TeamTag = apps.get_model('core', 'TeamTag')
    
    for tag in TeamTag.objects.all():
        # Set target to midpoint of range
        tag.target = (tag.target_min + tag.target_max) // 2
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_target_range_to_teamtag'),
    ]

    operations = [
        migrations.RunPython(migrate_target_to_range, reverse_migrate_target_to_range),
    ]