# Generated by Django 5.2.7 on 2025-10-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_migrate_target_to_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('INJURED', 'Injured'), ('SICK', 'Sick'), ('EXCUSED', 'Excused')], default='AVAILABLE', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_note',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
