# Generated by Django 5.2.7 on 2025-11-02 02:34

from django.db import migrations, models
import string
import secrets


def generate_join_code():
    """Generate a unique 6-character alphanumeric code."""
    alphabet = string.ascii_uppercase + string.digits
    while True:
        code = ''.join(secrets.choice(alphabet) for _ in range(6))
        # Check if code exists in database (simple check for migration)
        # We'll need to update existing teams after field is added
        return code


def backfill_join_codes(apps, schema_editor):
    """Generate join codes for all existing teams."""
    Team = apps.get_model('core', 'Team')
    alphabet = string.ascii_uppercase + string.digits
    existing_codes = set()
    
    for team in Team.objects.all():
        if not team.join_code:
            # Generate unique code
            while True:
                code = ''.join(secrets.choice(alphabet) for _ in range(6))
                if code not in existing_codes and not Team.objects.filter(join_code=code).exists():
                    existing_codes.add(code)
                    team.join_code = code
                    team.save()
                    break


def reverse_backfill(apps, schema_editor):
    """Reverse migration - clear join codes (optional)."""
    Team = apps.get_model('core', 'Team')
    Team.objects.all().update(join_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_current_status_profile_status_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='join_code',
            field=models.CharField(blank=True, editable=False, help_text='Unique code for joining this team', max_length=8, null=True, unique=True),
        ),
        migrations.RunPython(backfill_join_codes, reverse_backfill),
    ]
