# Generated by Django 5.2.7 on 2025-11-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone for daily reminders (e.g., 'America/New_York', 'Europe/London', 'UTC')", max_length=50),
        ),
    ]
