# Generated by Django 5.2.7 on 2025-11-05 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_timezone_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_reminder_enabled',
            field=models.BooleanField(default=True, help_text='Enable daily reminder emails at 12pm local time'),
        ),
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.team'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='core.team'),
        ),
    ]
