# Generated by Django 5.2.7 on 2025-11-10 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_team_logo_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for the feature request or bug', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the feature request or bug', max_length=2000)),
                ('request_type', models.CharField(choices=[('FEATURE', 'Feature Request'), ('BUG', 'Bug Report')], default='FEATURE', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upvoted_by', models.ManyToManyField(blank=True, related_name='upvoted_feature_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Request',
                'verbose_name_plural': 'Feature Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Your comment', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.featurerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_request_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Request Comment',
                'verbose_name_plural': 'Feature Request Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
